# -------- STAGE 1: Build --------
FROM eclipse-temurin:17-jdk AS builder

WORKDIR /app

COPY . .

RUN ./gradlew clean bootJar -x test

# -------- STAGE 2: Run --------
FROM eclipse-temurin:17-jre

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
